myproject/accounts/urls.py
from django.urls import path
from . import views as accounts_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('signup/', accounts_views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout" )
]

myproject/boards/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('boards/<int:pk>/', views.board_topics ,name='board_topics'),
    path('boards/<int:pk>/new/', views.new_topic, name="new_topic"),
    


]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('boards.urls')),
    path('account/', include('accounts.urls'))
]

myproject/accounts/models.py
from django.db import models

# Create your models here.

myproject/boards/models.py
from django.db import models
from django.contrib.auth.models import User

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name
class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.CASCADE)# related_name='+' instructs django that we don't need this reverse relationship

myproject/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

myproject/boards/forms.py
from django import forms
from .models import Topic

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(),
    max_length=4000)

    class Meta:
        model = Topic
        fields = ['subject', 'message']

myproject/accounts/views.py
from .forms import SignUpForm
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect

def signup(request):
    form = SignUpForm()
    
    if request.method =="POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form':form})
        

myproject/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404

from boards.forms import NewTopicForm
from .models import Board, Topic, Post
from django.contrib.auth.models import User
def home(request):
    boards = Board.objects.all()
    return render(request, 'home.html', {'boards': boards})
    
def board_topics(request, pk):
   
    # try:
    #     board=Board.objects.get(pk=pk)
    # except Board.DoesNotExist:
    #     raise Http404
    # return render(request, 'topics.html', {'board':board})

    board = get_object_or_404(Board, pk=pk)
    return render(request, 'topics.html', {'board':board})

# def new_topic(request, pk):
#     board = get_object_or_404(Board, pk=pk)
    
#     if request.method == 'POST':
#         subject = request.POST['subject']
#         message = request.POST['message']

#         user = User.objects.first() #get currently logged in user

#         topic = Topic.objects.create(
#             subject = subject,
#             board = board,
#             starter = user
#         )

#         post = Post.objects.create(
#             message=message,
#             topic = topic,
#             created_by = user
#         )

#         return redirect('board_topics', pk=board.pk)
#     return render(request, 'new_topic.html',{'board':board})

def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    user = User.objects.first()
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=user
            )
            return redirect('board_topics', pk=board.pk)
    else:
        form = NewTopicForm()
    return render(request, 'new_topic.html', {'board':board, 'form':form})

myproject/boards/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>{% block title %} Document {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    {% block stylesheet %}{% endblock %}
</head>
<body>
    {% block body %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">{{ user.username }}</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  {% endblock body %}
</body>
</html>

myproject/boards/templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li class="active text-white">Boards</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse bg-dark text-white">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards%}
      <tr>
        <td>
          <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
          <small class="text-muted d-block">{{ board.description}}</small>
        </td>
        <td class="align-middle">0</td>
        <td class="align-middle">0</td>
        <td></td>
      </tr>
      {% endfor%}
    </tbody>
  </table>
{% endblock %}

myproject/boards/templates/includes/form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
      {% endif %}
    </div>
  {% endfor %}

myproject/boards/templates/new_topic.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} Start a New Topic {% endblock%}

{% block breadcrumb%}
<li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name}}</a></li>
<li class="breadcrumb-item active">New topic</li>
{% endblock %}
{% block content%}
<!-- hard coded form not to be used in this way -->
    <!-- <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_subject">Subject</label>
            <input type="text" class="form-control" id="id_subject" name="subject">
        </div>
        <div class="form-group">
            <label for="id_message">Message</label>
            <textarea class='form-control' name="message" id="id_message" cols="30" rows="10"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Post</button>
    </form> -->
   
   <!-- form rendered using django form api -->
    <!-- <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success">Post</button>
    </form> -->

    <!-- form with widget_tweaks -->
    <!-- <form method="post" novalidate>
        {% csrf_token %} -->
        <!-- {% for field in form %}
        <div class="form-group">
            {{field.label_tag }}
            {% render_field field class='form-control'%}
        
            {% if field.help_text%}
            <small class="form-text text-muted">{{ field.help_text}}</small>
        
            {% endif %}

        </div>
        {% endfor %} -->

        
    
        <!-- <button type="submit" class="btn btn-success">Post</button> -->
      <!-- </form> -->



      <!-- adding bootstrap validation  -->
      <!-- <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {% if field.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid"%}
                        {% for error in errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                    {%else %}
                    {% render_field field class="form-control is-valid"%}
                    {%endif%}
                {% else %}
                    {% render_field field class="form-control"%}
                {%endif%}

                {% if field.help_text %}
                    <small class="form-text text-muted">
                        {{ field.help_text}}
                    </small>
                {% endif %}
            </div>
        
        {% endfor %}
        <button type="submit" class="btn btn-success">Post</button>
      </form> -->
<!-- 
      <form method="post" novalidate>
        {% csrf_token %}
      
        {% for field in form %}
          <div class="form-group">
            {{ field.label_tag }}
      
            {% if form.is_bound %}
              {% if field.errors %}
      
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                  <div class="invalid-feedback">
                    {{ error }}
                  </div>
                {% endfor %}

                {% else %}
                {% render_field field class="form-control is-valid" %}
              {% endif %}
            {% else %}
              {% render_field field class="form-control" %}
            {% endif %}
      
            {% if field.help_text %}
              <small class="form-text text-muted">
                {{ field.help_text }}
              </small>
            {% endif %}
          </div>
        {% endfor %}
      
        <button type="submit" class="btn btn-success">Post</button>
      <!-- <form> -->
       

        <!-- after adding common form.html -->
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html'%}
            <button type="submit" class="btn btn-success">Post</button>
        </form>

{% endblock %}

myproject/boards/templates/signup.html
{% extends 'base.html'%}

{% load static %}
{%block stylesheet%}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}
{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Django Boards</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Sign up</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Create an account</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Already have an account? <a href="#">Log in</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

myproject/boards/templates/topics.html
{% extends "base.html"%}

{% block title %}
 {{ board.name}} - {{block.super}}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"> <a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}
{% block content%}
    <div class="mb-4">
        <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New topic</a>
    </div>
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Topic</th>
                <th>Starter</th>
                <th>Replies</th>
                <th>Views</th>
                <th>Last Update</th>
            </tr>
        </thead>
        <tbody>
            {% for topic in board.topics.all %}
            <tr>
                <td>{{ topic.subject}}</td>
                <td>{{ topic.starter.username }}</td>
                <td>0</td>
                <td>0</td>
                <td>{{ topic.last_updated }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}